language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-20mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-21mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/50498825dcdd9275c0e8
    on_success: change
    on_failure: always
    on_start: false
