language: ruby
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake spec"
rvm:
  - 2.1.2
  - 2.2.2
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
